"""The committed ACS SLD packages regenerate from their witnessed bytes.

The six Utah state-legislative-district packages are generated by
``ledger.sources.census_acs_sld`` from the witnessed API responses. These
tests pin that relationship: a hand edit to a committed YAML, a drifted
generator, or a swapped witness file is a failure here, not a silent
divergence.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest
import yaml

from ledger.sources.census_acs_sld import (
    CHAMBERS,
    SLD_TABLES,
    _package_names,
    build_source_url,
    generate_manifest,
    generate_source_package,
    parse_witness_rows,
)

REPO_ROOT = Path(__file__).resolve().parent.parent
EXTRACTED_AT = "2026-08-05"
PILOT_STATE_FIPS = "49"


def _pilot_cases() -> list[tuple[str, str]]:
    return [
        (table_key, chamber_key) for table_key in SLD_TABLES for chamber_key in CHAMBERS
    ]


@pytest.mark.parametrize(("table_key", "chamber_key"), _pilot_cases())
def test_committed_package_yaml_regenerates_from_witnessed_bytes(
    table_key: str,
    chamber_key: str,
) -> None:
    names = _package_names(table_key, chamber_key, PILOT_STATE_FIPS)
    data_dir = REPO_ROOT / "db" / "data" / "census" / names["directory"]
    package_dir = REPO_ROOT / "packages" / "census" / names["directory"]
    content = (data_dir / names["filename"]).read_bytes()

    regenerated = generate_source_package(
        content,
        table_key=table_key,
        chamber_key=chamber_key,
        state_fips=PILOT_STATE_FIPS,
        extracted_at=EXTRACTED_AT,
    )
    committed = yaml.safe_load((package_dir / "source_package.yaml").read_text())
    assert regenerated == committed, names["directory"]


@pytest.mark.parametrize(("table_key", "chamber_key"), _pilot_cases())
def test_committed_manifest_matches_witnessed_bytes(
    table_key: str,
    chamber_key: str,
) -> None:
    names = _package_names(table_key, chamber_key, PILOT_STATE_FIPS)
    data_dir = REPO_ROOT / "db" / "data" / "census" / names["directory"]
    content = (data_dir / names["filename"]).read_bytes()

    regenerated = generate_manifest(
        content,
        table_key=table_key,
        chamber_key=chamber_key,
        state_fips=PILOT_STATE_FIPS,
    )
    committed = yaml.safe_load((data_dir / "manifest.yaml").read_text())
    # publish-raw appends storage.r2 blocks to committed file entries after
    # upload; everything the generator asserts must match exactly.
    committed_files = committed.get("files", {})
    for year_key, entry in regenerated["files"].items():
        committed_entry = dict(committed_files[year_key])
        committed_entry.pop("storage", None)
        assert committed_entry == entry, names["directory"]
    for key, value in regenerated.items():
        if key == "files":
            continue
        assert committed[key] == value, (names["directory"], key)


def test_source_urls_are_canonical_and_keyless() -> None:
    for table_key in SLD_TABLES:
        for chamber_key in CHAMBERS:
            url = build_source_url(table_key, chamber_key, PILOT_STATE_FIPS)
            assert url.startswith("https://api.census.gov/data/2024/acs/acs5")
            assert "key=" not in url
            assert "GEO_ID,NAME" in url
            assert f"in=state:{PILOT_STATE_FIPS}" in url
            chamber = "upper" if chamber_key == "upper" else "lower"
            assert f"({chamber}%20chamber)" in url


def test_witness_row_counts_match_utah_districts() -> None:
    for table_key in SLD_TABLES:
        for chamber_key, expected in (("upper", 29), ("lower", 75)):
            names = _package_names(table_key, chamber_key, PILOT_STATE_FIPS)
            content = (
                REPO_ROOT
                / "db"
                / "data"
                / "census"
                / names["directory"]
                / names["filename"]
            ).read_bytes()
            _header, rows = parse_witness_rows(content)
            assert len(rows) == expected, names["directory"]


def _witness(header: list[str], rows: list[list[str]]) -> bytes:
    return json.dumps([header, *rows]).encode()


def test_parse_witness_rows_refuses_unsorted_districts() -> None:
    content = _witness(
        ["GEO_ID", "NAME", "B19013_001E", "state", "sld"],
        [
            ["610U900US49002", "d2", "1", "49", "002"],
            ["610U900US49001", "d1", "1", "49", "001"],
        ],
    )
    with pytest.raises(ValueError, match="sorted"):
        parse_witness_rows(content)


def test_parse_witness_rows_refuses_duplicate_districts() -> None:
    content = _witness(
        ["GEO_ID", "NAME", "B19013_001E", "state", "sld"],
        [
            ["610U900US49001", "d1", "1", "49", "001"],
            ["610U900US49001", "d1", "1", "49", "001"],
        ],
    )
    with pytest.raises(ValueError, match="unique"):
        parse_witness_rows(content)


def test_generate_source_package_refuses_suppressed_values() -> None:
    content = _witness(
        ["GEO_ID", "NAME", "B19013_001E", "B19013_001M", "state", "sld"],
        [["610U900US49001", "d1", "-666666666", "0", "49", "001"]],
    )
    with pytest.raises(ValueError, match="Suppressed"):
        generate_source_package(
            content,
            table_key="b19013",
            chamber_key="upper",
            state_fips=PILOT_STATE_FIPS,
            extracted_at=EXTRACTED_AT,
        )


def test_generate_source_package_refuses_wrong_chamber_geoids() -> None:
    content = _witness(
        ["GEO_ID", "NAME", "B19013_001E", "B19013_001M", "state", "sld"],
        [["620L900US49001", "d1", "1", "0", "49", "001"]],
    )
    with pytest.raises(ValueError, match="summary level"):
        generate_source_package(
            content,
            table_key="b19013",
            chamber_key="upper",
            state_fips=PILOT_STATE_FIPS,
            extracted_at=EXTRACTED_AT,
        )
